In [20]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [5]:
df = pd.read_csv("Data/abalone.csv")

In [8]:
df.head()

,Type,LongestShell,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [10]:
df["Type"].value_counts()

Type
M    1528
I    1342
F    1307
Name: count, dtype: int64

In [11]:
encoder = LabelEncoder()
df["Type"] = encoder.fit_transform(df["Type"])

In [12]:
df.head()

,Type,LongestShell,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,2,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,2,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,0,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,2,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,1,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [84]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [85]:
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [86]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [61]:
x_train.shape

(3341, 8)

In [62]:
y_train.shape

(3341,)

In [28]:
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)

In [ ]:
y_pred

In [30]:
y_test.shape

(836,)

In [87]:
accuracy_score(y_test,y_pred)

0.5299043062200957

In [89]:
y_test[2678]

np.int64(2)

In [82]:
import numpy as np
from collections import Counter

class KNN:
    
    def __init__(self, k=3):
        self.k = k
        
    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train
        
    def predict(self, X_test):
        predictions = []
        
        for x in X_test:
            # 1. Compute distances
            distances = []
            for i, x_train in enumerate(self.X_train):
                dist = self.calculate_distance(x, x_train)
                distances.append((i, dist))
            
            # 2. Sort & select k nearest
            distances.sort(key=lambda x: x[1])
            k_neighbours = distances[:self.k]
            
            # 3. Get labels
            labels = [self.y_train[i[0]] for i in k_neighbours]
            
            # 4. Majority vote
            prediction = Counter(labels).most_common(1)[0][0]
            predictions.append(prediction)
            
        return predictions
    
    def calculate_distance(self, a, b):
        return np.linalg.norm(a - b)

In [92]:
mera_knn = KNN(k=5)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)

In [94]:
accuracy_score(y_test,y_pred)

0.5299043062200957