In [3]:
import pandas as pd
import requests
from io import StringIO
import mysql.connector

### Problem-1:

You are given a SQL file link: https://drive.google.com/file/d/1WFt7B84LTHhMueoKmz8W-PRo7xXqmZf3/view?usp=share_link. Read the data by using the file and store it in a excel file. In this data, there are 3 tables named "invoices", "order_leads" and "sales_sql". So create 3 sheets to your excel file.

In [43]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='temp_db')

In [45]:
invoices = pd.read_sql_query('SELECT * FROM invoices',conn)
orders_lead = pd.read_sql_query('SELECT * FROM orderleads',conn)
sales_team = pd.read_sql_query('SELECT * FROM orderleads',conn)

C:\Users\axitk\AppData\Local\Temp\ipykernel_8760\671692319.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  invoices = pd.read_sql_query('SELECT * FROM invoices',conn)
C:\Users\axitk\AppData\Local\Temp\ipykernel_8760\671692319.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders_lead = pd.read_sql_query('SELECT * FROM orderleads',conn)
C:\Users\axitk\AppData\Local\Temp\ipykernel_8760\671692319.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sales_team = pd.read_sql_query('SELECT * FROM orderleads',conn)

In [46]:
invoices.head()

,Order Id,Date,Meal Id,Company Id,Date of Meal,Participants,Meal Price,Type of Meal
0,839FKFW2LLX4LMBB,27-05-2016,INBUX904GIHI8YBD,LJKS5NK6788CYMUU,2016-05-31 07:00:00+02:00,['David Bishop'],469,Breakfast
1,97OX39BGVMHODLJM,27-09-2018,J0MMOOPP709DIDIE,LJKS5NK6788CYMUU,2018-10-01 20:00:00+02:00,['David Bishop'],22,Dinner
2,041ORQM5OIHTIU6L,24-08-2014,E4UJLQNCI16UX5CS,LJKS5NK6788CYMUU,2014-08-23 14:00:00+02:00,['Karen Stansell'],314,Lunch
3,YT796QI18WNGZ7ZJ,2014-12-04 00:00:00,C9SDFHF7553BE247,LJKS5NK6788CYMUU,2014-04-07 21:00:00+02:00,['Addie Patino'],438,Dinner
4,6YLROQT27B6HRF4E,28-07-2015,48EQXS6IHYNZDDZ5,LJKS5NK6788CYMUU,2015-07-27 14:00:00+02:00,['Addie Patino' 'Susan Guerrero'],690,Lunch

In [47]:
with pd.ExcelWriter('Supermarker.xlsx') as writer:
    invoices.to_excel(writer,sheet_name = 'Invoices')
    orders_lead.to_excel(writer,sheet_name = 'Order Lead')
    sales_team.to_excel(writer,sheet_name = 'Sales team')

### Problem-2

Go to the site: https://rapidapi.com/wirefreethought/api/geodb-cities. From here, you have to grab the API and have to choose proper routes to get the cities of different countries. After getting the right API, hit that API and create a dataframe of all the cities that you can get by using the API. Then store the dataframe to a SQL. If you need to create an account or have to subscribe, then do that (it has free subscription but has some limitations. Use that free subscription and modify your accordingly to get all the data).

In [11]:
import requests

url = "https://wft-geo-db.p.rapidapi.com/v1/geo/locations/33.832213-118.387099/nearbyCities"

querystring = {"radius":"100"}

headers = {
	"x-rapidapi-key": "47ccbde18dmsh4905a8fe3502b22p12ed60jsn38c7319a4c74",
	"x-rapidapi-host": "wft-geo-db.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

In [ ]:
responce = response.json()

In [21]:
df = pd.DataFrame(responce['data'])

In [98]:
import requests

url = "https://wft-geo-db.p.rapidapi.com/v1/geo/cities"

headers = {
	"x-rapidapi-key": "47ccbde18dmsh4905a8fe3502b22p12ed60jsn38c7319a4c74",
	"x-rapidapi-host": "wft-geo-db.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data = response.json()['data']
links = response.json()['links']
metadata = response.json()['metadata']

In [99]:
total_cities = metadata['totalCount']/5
next_url = links[1]['href']

In [100]:
df = pd.DataFrame(data)
df

,id,wikiDataId,type,city,name,country,countryCode,region,regionCode,regionWdId,latitude,longitude,population
0,3350606,Q24668,CITY,Aixirivall,Aixirivall,Andorra,AD,Sant Julià de Lòria,06,Q24282,42.462450,1.502090,1025
1,3216144,Q24656,CITY,Aixovall,Aixovall,Andorra,AD,Sant Julià de Lòria,06,Q24282,42.476358,1.489492,69
2,3406038,Q4699394,CITY,Aixàs,Aixàs,Andorra,AD,Sant Julià de Lòria,06,Q24282,42.486389,1.467222,0
3,397,Q1863,CITY,Andorra la Vella,Andorra la Vella,Andorra,AD,Andorra la Vella,07,Q2522163,42.507222,1.522222,24042
4,3360277,Q24475,CITY,Ansalonga,Ansalonga,Andorra,AD,Ordino,05,Q24272,42.568443,1.521571,0

In [103]:
for count in range(1,500):
    url = 'https://wft-geo-db.p.rapidapi.com'
    page= url+next_url
    response = requests.get(page, headers=headers)
    
    data = response.json()['data']
    links = response.json()['links']
    
    for item in links:
        if item['rel'] == 'next':
            next_url  = item['href']
    

    df = pd.concat([df,pd.DataFrame(data)],ignore_index=True)
    time.sleep(2)

KeyboardInterrupt:

In [104]:
df

,id,wikiDataId,type,city,name,country,countryCode,region,regionCode,regionWdId,latitude,longitude,population
0,3350606,Q24668,CITY,Aixirivall,Aixirivall,Andorra,AD,Sant Julià de Lòria,06,Q24282,42.462450,1.502090,1025
1,3216144,Q24656,CITY,Aixovall,Aixovall,Andorra,AD,Sant Julià de Lòria,06,Q24282,42.476358,1.489492,69
2,3406038,Q4699394,CITY,Aixàs,Aixàs,Andorra,AD,Sant Julià de Lòria,06,Q24282,42.486389,1.467222,0
3,397,Q1863,CITY,Andorra la Vella,Andorra la Vella,Andorra,AD,Andorra la Vella,07,Q2522163,42.507222,1.522222,24042
4,3360277,Q24475,CITY,Ansalonga,Ansalonga,Andorra,AD,Ordino,05,Q24272,42.568443,1.521571,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,3214790,Q2663252,ADM2,Dangam District,Dangam District,Afghanistan,AF,Kunar Province,KNR,Q188147,34.992500,71.418900,0
511,3410839,Q3696140,ADM2,Dara-I-Nur,Dara-I-Nur,Afghanistan,AF,Nangarhar Province,NAN,Q178471,34.706667,70.585833,0
512,3325693,Q2663248,ADM2,Dara-I-Pech,Dara-I-Pech,Afghanistan,AF,Kunar Province,KNR,Q188147,34.954444,70.816944,0
513,3296351,Q5222015,CITY,Darabad,Darabad,Afghanistan,AF,Balkh Province,BAL,Q121104,36.950278,66.927222,0
514,3415211,Q5222045,ADM2,Darah Hazara District,Darah Hazara District,Afghanistan,AF,Panjshir Province,PAN,Q181235,35.235556,69.770000,0

In [105]:
import pymysql
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:@localhost/Cities")
df.to_sql('Cities',con=engine,if_exists='append')

C:\Users\axitk\AppData\Local\Temp\ipykernel_8760\4045182879.py:4: UserWarning: The provided table name 'Cities' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql('Cities',con=engine,if_exists='append')

515

### Problem 3:

Go to this url: https://www.flipkart.com/search?q=smartphones. This is the url to find phones in flipkart website. You have to extract the below things:
1. image url of the phone
2. name of the image
3. average ratings
4. total ratings
5. total reviews
6. discounted price
7. actual price

Extract all the phones which are available in this website. So you have to use the pagination concept. **Also after requesting every page through the url, please wait for a while (minimum 2-3 seconds), otherwise your IP address can be banned to access the flipkart website later.**

After collecting all the data, save that in a JSON file.

In [117]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import timer
import numpy as np

In [41]:
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
webpage = requests.get('https://www.flipkart.com/search?q=smartphones&page=1',headers=headers).text

In [108]:
soup = BeautifulSoup(webpage)

In [149]:
all_div = soup.find_all('div',class_='tUxRFH')
df = pd.DataFrame()

In [ ]:
phone_url = []
phone_name = []
phone_stars = []
phone_rating = []
phone_price = []
previous_price = []
phone_review = []

for phone in all_div:
    try:
        phone_url.append(phone.find("img",class_='DByuf4')['src'])
    except:
        phone_url.append(np.nan)
    try:
        phone_name.append(phone.find("div",class_='KzDlHZ').text.strip())
    except:
        phone_name.append(np.nan)
    try:
        phone_stars.append(phone.find("div",class_='XQDdHH').text.strip())
    except:
        phone_stars.append(np.nan)

    try:
        phone_rating.append(phone.find_all("span",class_='Wphh3N')[0].find_all('span')[0].find_all('span')[0].text.strip())
    except:
        phone_rating.append(np.nan)
    
    try:
        phone_price.append(phone.find('div',class_='Nx9bqj _4b5DiR').text.strip())
    except:
        phone_price.append(np.nan)
    
    try:
        previous_price.append(phone.find('div',class_='yRaY8j ZYYwLA').text.strip())
    except:
        previous_price.append(np.nan)

    
    try:
        phone_review.append(phone.find_all("span",class_='Wphh3N')[0].find_all('span')[0].find_all('span')[2].text.strip())
        # print(phone.find_all("span",class_='Wphh3N')[0].find_all('span')[0].find_all('span')[2].text.strip())
    
    except:
        phone_review.append(np.nan)
    
    temp_df = pd.DataFrame({'Phone Name':phone_name,'Phone Price':phone_price,'Previous Price':previous_price,'Phone Stars':phone_stars,'Phone Rating':phone_rating,'Phone Reviews':phone_review,'Phone URL':phone_url})

(24, 7)

In [215]:
final_df = pd.DataFrame(columns=['Phone Name','Phone Price','Previous Price','Phone Stars','Phone Rating','Phone Reviews','Phone URL'])   

for i in range(1,10):
    headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
    webpage = requests.get('https://www.flipkart.com/search?q=smartphones&page={}'.format(i),headers=headers).text
    soup = BeautifulSoup(webpage)
    all_div = soup.find_all('div',class_='tUxRFH')

    
    phone_url = []
    phone_name = []
    phone_stars = []
    phone_rating = []
    phone_price = []
    previous_price = []
    phone_review = []

    for phone in all_div:
        try:
            phone_url.append(phone.find("img",class_='DByuf4')['src'])
        except:
            phone_url.append(np.nan)
        try:
            phone_name.append(phone.find("div",class_='KzDlHZ').text.strip())
        except:
            phone_name.append(np.nan)
        try:
            phone_stars.append(phone.find("div",class_='XQDdHH').text.strip())
        except:
            phone_stars.append(np.nan)

        try:
            phone_rating.append(phone.find_all("span",class_='Wphh3N')[0].find_all('span')[0].find_all('span')[0].text.strip())
        except:
            phone_rating.append(np.nan)
        
        try:
            phone_price.append(phone.find('div',class_='Nx9bqj _4b5DiR').text.strip())
        except:
            phone_price.append(np.nan)
        
        try:
            previous_price.append(phone.find('div',class_='yRaY8j ZYYwLA').text.strip())
        except:
            previous_price.append(np.nan)

        
        try:
            phone_review.append(phone.find_all("span",class_='Wphh3N')[0].find_all('span')[0].find_all('span')[2].text.strip())
            # print(phone.find_all("span",class_='Wphh3N')[0].find_all('span')[0].find_all('span')[2].text.strip())
        
        except:
            phone_review.append(np.nan)
        
        temp_df = pd.DataFrame({'Phone Name':phone_name,'Phone Price':phone_price,'Previous Price':previous_price,'Phone Stars':phone_stars,'Phone Rating':phone_rating,'Phone Reviews':phone_review,'Phone URL':phone_url})   

        # print(temp_df)
        final_df = pd.concat([final_df,temp_df],ignore_index=True)

In [216]:
final_df

,Phone Name,Phone Price,Previous Price,Phone Stars,Phone Rating,Phone Reviews,Phone URL
0,"Samsung Galaxy F05 (Twilight Blue, 64 GB)","₹6,249","₹9,999",4.2,"60,207 Ratings","3,476 Reviews",https://rukminim2.flixcart.com/image/312/312/x...
1,"Samsung Galaxy F05 (Twilight Blue, 64 GB)","₹6,249","₹9,999",4.2,"60,207 Ratings","3,476 Reviews",https://rukminim2.flixcart.com/image/312/312/x...
2,"MOTOROLA g05 (Forest Green, 64 GB)","₹6,999","₹9,999",4.2,"42,586 Ratings","3,084 Reviews",https://rukminim2.flixcart.com/image/312/312/x...
3,"Samsung Galaxy F05 (Twilight Blue, 64 GB)","₹6,249","₹9,999",4.2,"60,207 Ratings","3,476 Reviews",https://rukminim2.flixcart.com/image/312/312/x...
4,"MOTOROLA g05 (Forest Green, 64 GB)","₹6,999","₹9,999",4.2,"42,586 Ratings","3,084 Reviews",https://rukminim2.flixcart.com/image/312/312/x...
...,...,...,...,...,...,...,...
2695,"Apple iPhone 13 (Starlight, 128 GB)","₹44,999","₹49,900",4.6,"2,92,870 Ratings","13,972 Reviews",https://rukminim2.flixcart.com/image/312/312/k...
2696,"MOTOROLA Edge 60 Stylus (PANTONE Surf the Web,...","₹22,999","₹28,999",4.3,"7,737 Ratings",661 Reviews,https://rukminim2.flixcart.com/image/312/312/x...
2697,"Samsung Galaxy A55 5G (Awesome Iceblue, 128 GB)","₹26,624","₹42,999",4.4,"1,948 Ratings",150 Reviews,https://rukminim2.flixcart.com/image/312/312/x...
2698,"REDMI A4 5G only on Jio SIM (Starry Black, 128...","₹9,690","₹11,999",4.3,"6,866 Ratings",329 Reviews,https://rukminim2.flixcart.com/image/312/312/x...
2699,"POCO M7 Pro 5G (Lavender Frost, 256 GB)","₹14,999","₹20,999",4.2,"6,818 Ratings",702 Reviews,https://rukminim2.flixcart.com/image/312/312/x...