In [1]:
import pandas as pd

In [3]:
pd.read_excel('Data\Students_Marks.xlsx')

    Student Name  Math  Science  English  History
0  Alice Johnson    85       90       88       84
1      Bob Smith    78       82       79       75
2    Charlie Lee    92       95       93       90
3   Diana Prince    88       89       85       86
4    Ethan Clark    76       80       77       79

In [6]:
pd.read_excel('Data\Students_Marks.xlsx',sheet_name='Axit')

    Name  Marks
0   Axit    100
1  Jamay   1000

In [ ]:
#Working with a text file

pd.read_csv('data.txt',sep='\t') #reading a text data