In [2]:
import pandas as pd
df = pd.DataFrame()

In [4]:
df.to_csv('Empty')

# to csv

In [6]:
df = pd.read_csv('Data\deliveries.csv')
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [12]:
temp_df = df.groupby('batsman')['total_runs'].sum().sort_values(ascending=False).reset_index()

In [14]:
temp_df.to_csv('batsman_runs.csv',index=False)

In [17]:
df.pivot_table(index='batsman',columns='bowling_team',values='batsman_runs',aggfunc = 'sum').to_csv('Batsman_vs_Team.csv')

# to Excel File

In [19]:
temp_df

          batsman  total_runs
0        SK Raina        4745
1         V Kohli        4588
2       G Gambhir        4388
3       RG Sharma        4334
4       DA Warner        4213
..            ...         ...
456      L Ablish           0
457  Abdur Razzak           0
458   Sunny Gupta           0
459     IC Pandey           0
460        U Kaul           0

[461 rows x 2 columns]

In [20]:
temp_df.to_excel('batsman_runs.xlsx')

In [22]:
temp_df.to_excel('batsman_runs.xlsx',sheet_name = 'Runs')

In [23]:
temp_df1 = df.pivot_table(index='bowler',columns='batting_team',values='total_runs',aggfunc = 'sum')
temp_df1

batting_team,Chennai Super Kings,Deccan Chargers,Delhi Daredevils,Gujarat Lions,Kings XI Punjab,Kochi Tuskers Kerala,Kolkata Knight Riders,Mumbai Indians,Pune Warriors,Rajasthan Royals,Rising Pune Supergiant,Rising Pune Supergiants,Royal Challengers Bangalore,Sunrisers Hyderabad
bowler,,,,,,,,,,,,,,
A Ashish Reddy,50.0,NaN,45.0,NaN,40.0,NaN,29.0,11.0,85.0,22.0,NaN,NaN,118.0,NaN
A Chandila,16.0,21.0,NaN,NaN,38.0,NaN,NaN,32.0,36.0,NaN,NaN,NaN,89.0,13.0
A Choudhary,NaN,NaN,NaN,21.0,17.0,NaN,19.0,32.0,NaN,NaN,NaN,NaN,NaN,55.0
A Flintoff,NaN,NaN,50.0,NaN,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,11.0,NaN
A Kumble,121.0,244.0,127.0,NaN,193.0,NaN,104.0,187.0,NaN,113.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YA Abdulla,18.0,NaN,50.0,NaN,NaN,NaN,54.0,20.0,NaN,65.0,NaN,NaN,104.0,NaN
YK Pathan,303.0,168.0,96.0,21.0,177.0,37.0,114.0,122.0,59.0,62.0,NaN,NaN,149.0,113.0
YS Chahal,156.0,NaN,192.0,155.0,211.0,NaN,286.0,214.0,NaN,86.0,36.0,38.0,NaN,226.0
Yuvraj Singh,116.0,129.0,198.0,13.0,85.0,12.0,81.0,124.0,NaN,148.0,NaN,10.0,124.0,28.0
Z Khan,360.0,188.0,246.0,110.0,409.0,57.0,427.0,299.0,91.0,224.0,45.0,19.0,260.0,125.0

In [24]:
with pd.ExcelWriter('output.xlsx') as writer:
    temp_df.to_excel(writer,sheet_name='Batsman Runs')
    temp_df1.to_excel(writer,sheet_name='Bowler Runs')

# to_html

In [30]:
df.query('batsman_runs == 6').pivot_table(index='over',columns='ball',values='batsman_runs',aggfunc='count').to_html('Sixes_heatmap.html')

# to_JSON

In [33]:
df.groupby(['batting_team','batsman'])['batsman_runs'].sum().unstack().to_json('IPL_run.json')

# to_sql

In [ ]:
import mysql
from sqlalchemy import create_engine

In [ ]:
engine = create_engine("my_sql+pymysql://root:@localhost/ipl")
# {root}:{password}@{url}/{database}
df.to_sql({name of database},con=engine,if_exists='append')